### ISSUE TITLE
Problem with berserk

### ISSUE THREAD

**Issue by 9acca9** [cyanfish/python-lichess#9]
Hi.
Im doing some changes to your work. But dont touch anything on __main__.py

Can you tell me what could be related to this:

```
python3 __main__.py 
Traceback (most recent call last):
  File "__main__.py", line 82, in <module>
    main()
  File "__main__.py", line 34, in main
    account_data = client.account.get()
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/clients.py", line 115, in get
    return self._r.get(path, converter=models.Account.convert)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/session.py", line 60, in get
    return self.request('GET', *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/session.py", line 56, in request
    return fmt.handle(response, is_stream=is_stream, converter=converter)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/formats.py", line 35, in handle
    return converter(self.parse(response))
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/formats.py", line 76, in parse
    return response.json(cls=self.decoder)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 535, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

Thanks.

**Comment by cyanfish** [comment]
There's an issue with your decoder implementation

**Comment by 9acca9** [comment]
@cyanfish Sorry my ignorance... but i dont change nothing, except things related to game.py how take and thinks like that.
i dont do nothing related to "decoder implementation".
You can guide me a little here please?

**Comment by cyanfish** [comment]
Oh I see, you're posting on the wrong repository. This is a different project.
